version: '3'

services:
    ros-foxy-panda:
        build:
            context: .
            args:
                - ROS_DISTRO=foxy
        image: ros-foxy-panda
        user: admin:1000
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities:
                            - gpu
        stdin_open: true
        tty: true
        privileged: true
        network_mode: "host"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /dev/shm:/dev/shm
            - /dev/*:/dev/*
            - ../../../franka_ros2:/home/admin/colcon_panda_ws/src/
        environment:
            - DISPLAY=$DISPLAY
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"
# ros2 pkg create panda_ros2_goal --build-type ament_cmake --dependencies rclcpp geometry_msgs moveit
